// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package system

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func SystemDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Unique Identifier of the system, usually a UUID.",
				MarkdownDescription: "Unique Identifier of the system, usually a UUID.",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "A system specified name for the resource.",
				MarkdownDescription: "A system specified name for the resource.",
			},
		},
	}
}

type SystemModel struct {
	Id   types.String `tfsdk:"id"`
	Name types.String `tfsdk:"name"`
}
