package virtualmachines
type VirtualMachinesGetResponse_items_allowedOperations int

const (
    VIRTUAL_MACHINE_POWER_ON_VIRTUALMACHINESGETRESPONSE_ITEMS_ALLOWEDOPERATIONS VirtualMachinesGetResponse_items_allowedOperations = iota
    VIRTUAL_MACHINE_POWER_OFF_VIRTUALMACHINESGETRESPONSE_ITEMS_ALLOWEDOPERATIONS
    VIRTUAL_MACHINE_RESET_VIRTUALMACHINESGETRESPONSE_ITEMS_ALLOWEDOPERATIONS
    VIRTUAL_MACHINE_SHUTDOWN_GUEST_OS_VIRTUALMACHINESGETRESPONSE_ITEMS_ALLOWEDOPERATIONS
    VIRTUAL_MACHINE_RESTART_GUEST_OS_VIRTUALMACHINESGETRESPONSE_ITEMS_ALLOWEDOPERATIONS
    VIRTUAL_MACHINE_DELETE_VIRTUALMACHINESGETRESPONSE_ITEMS_ALLOWEDOPERATIONS
    VIRTUAL_MACHINE_BACKUP_CREATE_VIRTUALMACHINESGETRESPONSE_ITEMS_ALLOWEDOPERATIONS
    VIRTUAL_MACHINE_BACKUP_UPDATE_VIRTUALMACHINESGETRESPONSE_ITEMS_ALLOWEDOPERATIONS
    VIRTUAL_MACHINE_BACKUP_DELETE_VIRTUALMACHINESGETRESPONSE_ITEMS_ALLOWEDOPERATIONS
    VIRTUAL_MACHINE_SNAPSHOT_CREATE_VIRTUALMACHINESGETRESPONSE_ITEMS_ALLOWEDOPERATIONS
    VIRTUAL_MACHINE_SNAPSHOT_UPDATE_VIRTUALMACHINESGETRESPONSE_ITEMS_ALLOWEDOPERATIONS
    VIRTUAL_MACHINE_SNAPSHOT_DELETE_VIRTUALMACHINESGETRESPONSE_ITEMS_ALLOWEDOPERATIONS
    VIRTUAL_MACHINE_RESTORE_VIRTUALMACHINESGETRESPONSE_ITEMS_ALLOWEDOPERATIONS
    VIRTUAL_MACHINE_DISKS_RESTORE_VIRTUALMACHINESGETRESPONSE_ITEMS_ALLOWEDOPERATIONS
)

func (i VirtualMachinesGetResponse_items_allowedOperations) String() string {
    return []string{"VIRTUAL_MACHINE_POWER_ON", "VIRTUAL_MACHINE_POWER_OFF", "VIRTUAL_MACHINE_RESET", "VIRTUAL_MACHINE_SHUTDOWN_GUEST_OS", "VIRTUAL_MACHINE_RESTART_GUEST_OS", "VIRTUAL_MACHINE_DELETE", "VIRTUAL_MACHINE_BACKUP_CREATE", "VIRTUAL_MACHINE_BACKUP_UPDATE", "VIRTUAL_MACHINE_BACKUP_DELETE", "VIRTUAL_MACHINE_SNAPSHOT_CREATE", "VIRTUAL_MACHINE_SNAPSHOT_UPDATE", "VIRTUAL_MACHINE_SNAPSHOT_DELETE", "VIRTUAL_MACHINE_RESTORE", "VIRTUAL_MACHINE_DISKS_RESTORE"}[i]
}
func ParseVirtualMachinesGetResponse_items_allowedOperations(v string) (any, error) {
    result := VIRTUAL_MACHINE_POWER_ON_VIRTUALMACHINESGETRESPONSE_ITEMS_ALLOWEDOPERATIONS
    switch v {
        case "VIRTUAL_MACHINE_POWER_ON":
            result = VIRTUAL_MACHINE_POWER_ON_VIRTUALMACHINESGETRESPONSE_ITEMS_ALLOWEDOPERATIONS
        case "VIRTUAL_MACHINE_POWER_OFF":
            result = VIRTUAL_MACHINE_POWER_OFF_VIRTUALMACHINESGETRESPONSE_ITEMS_ALLOWEDOPERATIONS
        case "VIRTUAL_MACHINE_RESET":
            result = VIRTUAL_MACHINE_RESET_VIRTUALMACHINESGETRESPONSE_ITEMS_ALLOWEDOPERATIONS
        case "VIRTUAL_MACHINE_SHUTDOWN_GUEST_OS":
            result = VIRTUAL_MACHINE_SHUTDOWN_GUEST_OS_VIRTUALMACHINESGETRESPONSE_ITEMS_ALLOWEDOPERATIONS
        case "VIRTUAL_MACHINE_RESTART_GUEST_OS":
            result = VIRTUAL_MACHINE_RESTART_GUEST_OS_VIRTUALMACHINESGETRESPONSE_ITEMS_ALLOWEDOPERATIONS
        case "VIRTUAL_MACHINE_DELETE":
            result = VIRTUAL_MACHINE_DELETE_VIRTUALMACHINESGETRESPONSE_ITEMS_ALLOWEDOPERATIONS
        case "VIRTUAL_MACHINE_BACKUP_CREATE":
            result = VIRTUAL_MACHINE_BACKUP_CREATE_VIRTUALMACHINESGETRESPONSE_ITEMS_ALLOWEDOPERATIONS
        case "VIRTUAL_MACHINE_BACKUP_UPDATE":
            result = VIRTUAL_MACHINE_BACKUP_UPDATE_VIRTUALMACHINESGETRESPONSE_ITEMS_ALLOWEDOPERATIONS
        case "VIRTUAL_MACHINE_BACKUP_DELETE":
            result = VIRTUAL_MACHINE_BACKUP_DELETE_VIRTUALMACHINESGETRESPONSE_ITEMS_ALLOWEDOPERATIONS
        case "VIRTUAL_MACHINE_SNAPSHOT_CREATE":
            result = VIRTUAL_MACHINE_SNAPSHOT_CREATE_VIRTUALMACHINESGETRESPONSE_ITEMS_ALLOWEDOPERATIONS
        case "VIRTUAL_MACHINE_SNAPSHOT_UPDATE":
            result = VIRTUAL_MACHINE_SNAPSHOT_UPDATE_VIRTUALMACHINESGETRESPONSE_ITEMS_ALLOWEDOPERATIONS
        case "VIRTUAL_MACHINE_SNAPSHOT_DELETE":
            result = VIRTUAL_MACHINE_SNAPSHOT_DELETE_VIRTUALMACHINESGETRESPONSE_ITEMS_ALLOWEDOPERATIONS
        case "VIRTUAL_MACHINE_RESTORE":
            result = VIRTUAL_MACHINE_RESTORE_VIRTUALMACHINESGETRESPONSE_ITEMS_ALLOWEDOPERATIONS
        case "VIRTUAL_MACHINE_DISKS_RESTORE":
            result = VIRTUAL_MACHINE_DISKS_RESTORE_VIRTUALMACHINESGETRESPONSE_ITEMS_ALLOWEDOPERATIONS
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeVirtualMachinesGetResponse_items_allowedOperations(values []VirtualMachinesGetResponse_items_allowedOperations) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i VirtualMachinesGetResponse_items_allowedOperations) isMultiValue() bool {
    return false
}
