package virtualization

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// V1beta1CspAccountsItemCspSubscriptionsItemWithSubscriptionResponse a subscription whose values are defined by, and synchronized with, a cloud service provider.
// Deprecated: This class is obsolete. Use V1beta1CspAccountsItemCspSubscriptionsItemWithSubscriptionGetResponseable instead.
type V1beta1CspAccountsItemCspSubscriptionsItemWithSubscriptionResponse struct {
    V1beta1CspAccountsItemCspSubscriptionsItemWithSubscriptionGetResponse
}
// NewV1beta1CspAccountsItemCspSubscriptionsItemWithSubscriptionResponse instantiates a new V1beta1CspAccountsItemCspSubscriptionsItemWithSubscriptionResponse and sets the default values.
func NewV1beta1CspAccountsItemCspSubscriptionsItemWithSubscriptionResponse()(*V1beta1CspAccountsItemCspSubscriptionsItemWithSubscriptionResponse) {
    m := &V1beta1CspAccountsItemCspSubscriptionsItemWithSubscriptionResponse{
        V1beta1CspAccountsItemCspSubscriptionsItemWithSubscriptionGetResponse: *NewV1beta1CspAccountsItemCspSubscriptionsItemWithSubscriptionGetResponse(),
    }
    return m
}
// CreateV1beta1CspAccountsItemCspSubscriptionsItemWithSubscriptionResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateV1beta1CspAccountsItemCspSubscriptionsItemWithSubscriptionResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewV1beta1CspAccountsItemCspSubscriptionsItemWithSubscriptionResponse(), nil
}
// Deprecated: This class is obsolete. Use V1beta1CspAccountsItemCspSubscriptionsItemWithSubscriptionGetResponseable instead.
type V1beta1CspAccountsItemCspSubscriptionsItemWithSubscriptionResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    V1beta1CspAccountsItemCspSubscriptionsItemWithSubscriptionGetResponseable
}
