package virtualization

import (
    i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// V1beta1CspAccountsItemAccountGetResponse basic properties of a cloud service provider account
type V1beta1CspAccountsItemAccountGetResponse struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // ID assigned to the account by the cloud service provider
    cspId *string
    // The inventoryRefreshInfo property
    inventoryRefreshInfo []V1beta1CspAccountsItemAccountGetResponse_inventoryRefreshInfoable
    // The onboardingTemplate property
    onboardingTemplate V1beta1CspAccountsItemAccountGetResponse_onboardingTemplateable
    // Services (such as Backup and Recovery) currently associated with the CSP account
    services []string
    // Indicates whether actions against the cloud service provider account have been suspended
    suspended *bool
    // When the account was last validated
    validatedAt *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // Error messages generated by the last validation attempt
    validationErrors []string
}
// NewV1beta1CspAccountsItemAccountGetResponse instantiates a new V1beta1CspAccountsItemAccountGetResponse and sets the default values.
func NewV1beta1CspAccountsItemAccountGetResponse()(*V1beta1CspAccountsItemAccountGetResponse) {
    m := &V1beta1CspAccountsItemAccountGetResponse{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateV1beta1CspAccountsItemAccountGetResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateV1beta1CspAccountsItemAccountGetResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewV1beta1CspAccountsItemAccountGetResponse(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *V1beta1CspAccountsItemAccountGetResponse) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetCspId gets the cspId property value. ID assigned to the account by the cloud service provider
// returns a *string when successful
func (m *V1beta1CspAccountsItemAccountGetResponse) GetCspId()(*string) {
    return m.cspId
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *V1beta1CspAccountsItemAccountGetResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["cspId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCspId(val)
        }
        return nil
    }
    res["inventoryRefreshInfo"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateV1beta1CspAccountsItemAccountGetResponse_inventoryRefreshInfoFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]V1beta1CspAccountsItemAccountGetResponse_inventoryRefreshInfoable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(V1beta1CspAccountsItemAccountGetResponse_inventoryRefreshInfoable)
                }
            }
            m.SetInventoryRefreshInfo(res)
        }
        return nil
    }
    res["onboardingTemplate"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateV1beta1CspAccountsItemAccountGetResponse_onboardingTemplateFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetOnboardingTemplate(val.(V1beta1CspAccountsItemAccountGetResponse_onboardingTemplateable))
        }
        return nil
    }
    res["services"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfPrimitiveValues("string")
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]string, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = *(v.(*string))
                }
            }
            m.SetServices(res)
        }
        return nil
    }
    res["suspended"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSuspended(val)
        }
        return nil
    }
    res["validatedAt"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetValidatedAt(val)
        }
        return nil
    }
    res["validationErrors"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfPrimitiveValues("string")
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]string, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = *(v.(*string))
                }
            }
            m.SetValidationErrors(res)
        }
        return nil
    }
    return res
}
// GetInventoryRefreshInfo gets the inventoryRefreshInfo property value. The inventoryRefreshInfo property
// returns a []V1beta1CspAccountsItemAccountGetResponse_inventoryRefreshInfoable when successful
func (m *V1beta1CspAccountsItemAccountGetResponse) GetInventoryRefreshInfo()([]V1beta1CspAccountsItemAccountGetResponse_inventoryRefreshInfoable) {
    return m.inventoryRefreshInfo
}
// GetOnboardingTemplate gets the onboardingTemplate property value. The onboardingTemplate property
// returns a V1beta1CspAccountsItemAccountGetResponse_onboardingTemplateable when successful
func (m *V1beta1CspAccountsItemAccountGetResponse) GetOnboardingTemplate()(V1beta1CspAccountsItemAccountGetResponse_onboardingTemplateable) {
    return m.onboardingTemplate
}
// GetServices gets the services property value. Services (such as Backup and Recovery) currently associated with the CSP account
// returns a []string when successful
func (m *V1beta1CspAccountsItemAccountGetResponse) GetServices()([]string) {
    return m.services
}
// GetSuspended gets the suspended property value. Indicates whether actions against the cloud service provider account have been suspended
// returns a *bool when successful
func (m *V1beta1CspAccountsItemAccountGetResponse) GetSuspended()(*bool) {
    return m.suspended
}
// GetValidatedAt gets the validatedAt property value. When the account was last validated
// returns a *Time when successful
func (m *V1beta1CspAccountsItemAccountGetResponse) GetValidatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.validatedAt
}
// GetValidationErrors gets the validationErrors property value. Error messages generated by the last validation attempt
// returns a []string when successful
func (m *V1beta1CspAccountsItemAccountGetResponse) GetValidationErrors()([]string) {
    return m.validationErrors
}
// Serialize serializes information the current object
func (m *V1beta1CspAccountsItemAccountGetResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("cspId", m.GetCspId())
        if err != nil {
            return err
        }
    }
    if m.GetInventoryRefreshInfo() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetInventoryRefreshInfo()))
        for i, v := range m.GetInventoryRefreshInfo() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("inventoryRefreshInfo", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("onboardingTemplate", m.GetOnboardingTemplate())
        if err != nil {
            return err
        }
    }
    if m.GetServices() != nil {
        err := writer.WriteCollectionOfStringValues("services", m.GetServices())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("suspended", m.GetSuspended())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteTimeValue("validatedAt", m.GetValidatedAt())
        if err != nil {
            return err
        }
    }
    if m.GetValidationErrors() != nil {
        err := writer.WriteCollectionOfStringValues("validationErrors", m.GetValidationErrors())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *V1beta1CspAccountsItemAccountGetResponse) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetCspId sets the cspId property value. ID assigned to the account by the cloud service provider
func (m *V1beta1CspAccountsItemAccountGetResponse) SetCspId(value *string)() {
    m.cspId = value
}
// SetInventoryRefreshInfo sets the inventoryRefreshInfo property value. The inventoryRefreshInfo property
func (m *V1beta1CspAccountsItemAccountGetResponse) SetInventoryRefreshInfo(value []V1beta1CspAccountsItemAccountGetResponse_inventoryRefreshInfoable)() {
    m.inventoryRefreshInfo = value
}
// SetOnboardingTemplate sets the onboardingTemplate property value. The onboardingTemplate property
func (m *V1beta1CspAccountsItemAccountGetResponse) SetOnboardingTemplate(value V1beta1CspAccountsItemAccountGetResponse_onboardingTemplateable)() {
    m.onboardingTemplate = value
}
// SetServices sets the services property value. Services (such as Backup and Recovery) currently associated with the CSP account
func (m *V1beta1CspAccountsItemAccountGetResponse) SetServices(value []string)() {
    m.services = value
}
// SetSuspended sets the suspended property value. Indicates whether actions against the cloud service provider account have been suspended
func (m *V1beta1CspAccountsItemAccountGetResponse) SetSuspended(value *bool)() {
    m.suspended = value
}
// SetValidatedAt sets the validatedAt property value. When the account was last validated
func (m *V1beta1CspAccountsItemAccountGetResponse) SetValidatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.validatedAt = value
}
// SetValidationErrors sets the validationErrors property value. Error messages generated by the last validation attempt
func (m *V1beta1CspAccountsItemAccountGetResponse) SetValidationErrors(value []string)() {
    m.validationErrors = value
}
type V1beta1CspAccountsItemAccountGetResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetCspId()(*string)
    GetInventoryRefreshInfo()([]V1beta1CspAccountsItemAccountGetResponse_inventoryRefreshInfoable)
    GetOnboardingTemplate()(V1beta1CspAccountsItemAccountGetResponse_onboardingTemplateable)
    GetServices()([]string)
    GetSuspended()(*bool)
    GetValidatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetValidationErrors()([]string)
    SetCspId(value *string)()
    SetInventoryRefreshInfo(value []V1beta1CspAccountsItemAccountGetResponse_inventoryRefreshInfoable)()
    SetOnboardingTemplate(value V1beta1CspAccountsItemAccountGetResponse_onboardingTemplateable)()
    SetServices(value []string)()
    SetSuspended(value *bool)()
    SetValidatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetValidationErrors(value []string)()
}
