package virtualization

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// V1beta1HypervisorManagersItemHypervisorLibraryImagesItemHypervisorLibraryImageResponse represents a single instance of a hypervisor library image
// Deprecated: This class is obsolete. Use V1beta1HypervisorManagersItemHypervisorLibraryImagesItemHypervisorLibraryImageGetResponseable instead.
type V1beta1HypervisorManagersItemHypervisorLibraryImagesItemHypervisorLibraryImageResponse struct {
    V1beta1HypervisorManagersItemHypervisorLibraryImagesItemHypervisorLibraryImageGetResponse
}
// NewV1beta1HypervisorManagersItemHypervisorLibraryImagesItemHypervisorLibraryImageResponse instantiates a new V1beta1HypervisorManagersItemHypervisorLibraryImagesItemHypervisorLibraryImageResponse and sets the default values.
func NewV1beta1HypervisorManagersItemHypervisorLibraryImagesItemHypervisorLibraryImageResponse()(*V1beta1HypervisorManagersItemHypervisorLibraryImagesItemHypervisorLibraryImageResponse) {
    m := &V1beta1HypervisorManagersItemHypervisorLibraryImagesItemHypervisorLibraryImageResponse{
        V1beta1HypervisorManagersItemHypervisorLibraryImagesItemHypervisorLibraryImageGetResponse: *NewV1beta1HypervisorManagersItemHypervisorLibraryImagesItemHypervisorLibraryImageGetResponse(),
    }
    return m
}
// CreateV1beta1HypervisorManagersItemHypervisorLibraryImagesItemHypervisorLibraryImageResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateV1beta1HypervisorManagersItemHypervisorLibraryImagesItemHypervisorLibraryImageResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewV1beta1HypervisorManagersItemHypervisorLibraryImagesItemHypervisorLibraryImageResponse(), nil
}
// Deprecated: This class is obsolete. Use V1beta1HypervisorManagersItemHypervisorLibraryImagesItemHypervisorLibraryImageGetResponseable instead.
type V1beta1HypervisorManagersItemHypervisorLibraryImagesItemHypervisorLibraryImageResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    V1beta1HypervisorManagersItemHypervisorLibraryImagesItemHypervisorLibraryImageGetResponseable
}
