package virtualization

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// V1beta1CspAccountsItemCspResourceGroupsItemWithResourceGroupResponse a resource group whose values are defined by, and synchronized with, a cloud service provider.
// Deprecated: This class is obsolete. Use V1beta1CspAccountsItemCspResourceGroupsItemWithResourceGroupGetResponseable instead.
type V1beta1CspAccountsItemCspResourceGroupsItemWithResourceGroupResponse struct {
    V1beta1CspAccountsItemCspResourceGroupsItemWithResourceGroupGetResponse
}
// NewV1beta1CspAccountsItemCspResourceGroupsItemWithResourceGroupResponse instantiates a new V1beta1CspAccountsItemCspResourceGroupsItemWithResourceGroupResponse and sets the default values.
func NewV1beta1CspAccountsItemCspResourceGroupsItemWithResourceGroupResponse()(*V1beta1CspAccountsItemCspResourceGroupsItemWithResourceGroupResponse) {
    m := &V1beta1CspAccountsItemCspResourceGroupsItemWithResourceGroupResponse{
        V1beta1CspAccountsItemCspResourceGroupsItemWithResourceGroupGetResponse: *NewV1beta1CspAccountsItemCspResourceGroupsItemWithResourceGroupGetResponse(),
    }
    return m
}
// CreateV1beta1CspAccountsItemCspResourceGroupsItemWithResourceGroupResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateV1beta1CspAccountsItemCspResourceGroupsItemWithResourceGroupResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewV1beta1CspAccountsItemCspResourceGroupsItemWithResourceGroupResponse(), nil
}
// Deprecated: This class is obsolete. Use V1beta1CspAccountsItemCspResourceGroupsItemWithResourceGroupGetResponseable instead.
type V1beta1CspAccountsItemCspResourceGroupsItemWithResourceGroupResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    V1beta1CspAccountsItemCspResourceGroupsItemWithResourceGroupGetResponseable
}
