package item
// Resource Component Redundancy Status. Indicated as ENUM with following mapping
type WithServerGetResponse_health_powerSuppliesRedundancy int

const (
    REDUNDANT_WITHSERVERGETRESPONSE_HEALTH_POWERSUPPLIESREDUNDANCY WithServerGetResponse_health_powerSuppliesRedundancy = iota
    NONREDUNDANT_WITHSERVERGETRESPONSE_HEALTH_POWERSUPPLIESREDUNDANCY
    FAILEDREDUNDANT_WITHSERVERGETRESPONSE_HEALTH_POWERSUPPLIESREDUNDANCY
    ABSENT_WITHSERVERGETRESPONSE_HEALTH_POWERSUPPLIESREDUNDANCY
    DISABLED_WITHSERVERGETRESPONSE_HEALTH_POWERSUPPLIESREDUNDANCY
    OFFLINE_WITHSERVERGETRESPONSE_HEALTH_POWERSUPPLIESREDUNDANCY
    UNAVAILABLEOFFLINE_WITHSERVERGETRESPONSE_HEALTH_POWERSUPPLIESREDUNDANCY
    STANDBYOFFLINE_WITHSERVERGETRESPONSE_HEALTH_POWERSUPPLIESREDUNDANCY
    UNKNOWN_WITHSERVERGETRESPONSE_HEALTH_POWERSUPPLIESREDUNDANCY
)

func (i WithServerGetResponse_health_powerSuppliesRedundancy) String() string {
    return []string{"REDUNDANT", "NONREDUNDANT", "FAILEDREDUNDANT", "ABSENT", "DISABLED", "OFFLINE", "UNAVAILABLEOFFLINE", "STANDBYOFFLINE", "UNKNOWN"}[i]
}
func ParseWithServerGetResponse_health_powerSuppliesRedundancy(v string) (any, error) {
    result := REDUNDANT_WITHSERVERGETRESPONSE_HEALTH_POWERSUPPLIESREDUNDANCY
    switch v {
        case "REDUNDANT":
            result = REDUNDANT_WITHSERVERGETRESPONSE_HEALTH_POWERSUPPLIESREDUNDANCY
        case "NONREDUNDANT":
            result = NONREDUNDANT_WITHSERVERGETRESPONSE_HEALTH_POWERSUPPLIESREDUNDANCY
        case "FAILEDREDUNDANT":
            result = FAILEDREDUNDANT_WITHSERVERGETRESPONSE_HEALTH_POWERSUPPLIESREDUNDANCY
        case "ABSENT":
            result = ABSENT_WITHSERVERGETRESPONSE_HEALTH_POWERSUPPLIESREDUNDANCY
        case "DISABLED":
            result = DISABLED_WITHSERVERGETRESPONSE_HEALTH_POWERSUPPLIESREDUNDANCY
        case "OFFLINE":
            result = OFFLINE_WITHSERVERGETRESPONSE_HEALTH_POWERSUPPLIESREDUNDANCY
        case "UNAVAILABLEOFFLINE":
            result = UNAVAILABLEOFFLINE_WITHSERVERGETRESPONSE_HEALTH_POWERSUPPLIESREDUNDANCY
        case "STANDBYOFFLINE":
            result = STANDBYOFFLINE_WITHSERVERGETRESPONSE_HEALTH_POWERSUPPLIESREDUNDANCY
        case "UNKNOWN":
            result = UNKNOWN_WITHSERVERGETRESPONSE_HEALTH_POWERSUPPLIESREDUNDANCY
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeWithServerGetResponse_health_powerSuppliesRedundancy(values []WithServerGetResponse_health_powerSuppliesRedundancy) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i WithServerGetResponse_health_powerSuppliesRedundancy) isMultiValue() bool {
    return false
}
