// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package secret

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func SecretDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The UUID of the secret",
				MarkdownDescription: "The UUID of the secret",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the secret",
				MarkdownDescription: "The name of the secret",
			},
		},
	}
}

type SecretModel struct {
	Id   types.String `tfsdk:"id"`
	Name types.String `tfsdk:"name"`
}
