package item
type DatastoresGetResponse_allowedOperations int

const (
    DATASTORE_CREATE_DATASTORESGETRESPONSE_ALLOWEDOPERATIONS DatastoresGetResponse_allowedOperations = iota
    DATASTORE_DELETE_DATASTORESGETRESPONSE_ALLOWEDOPERATIONS
    DATASTORE_BACKUP_CREATE_DATASTORESGETRESPONSE_ALLOWEDOPERATIONS
    DATASTORE_BACKUP_UPDATE_DATASTORESGETRESPONSE_ALLOWEDOPERATIONS
    DATASTORE_BACKUP_DELETE_DATASTORESGETRESPONSE_ALLOWEDOPERATIONS
    DATASTORE_SNAPSHOT_CREATE_DATASTORESGETRESPONSE_ALLOWEDOPERATIONS
    DATASTORE_SNAPSHOT_UPDATE_DATASTORESGETRESPONSE_ALLOWEDOPERATIONS
    DATASTORE_SNAPSHOT_DELETE_DATASTORESGETRESPONSE_ALLOWEDOPERATIONS
    DATASTORE_RESTORE_DATASTORESGETRESPONSE_ALLOWEDOPERATIONS
)

func (i DatastoresGetResponse_allowedOperations) String() string {
    return []string{"DATASTORE_CREATE", "DATASTORE_DELETE", "DATASTORE_BACKUP_CREATE", "DATASTORE_BACKUP_UPDATE", "DATASTORE_BACKUP_DELETE", "DATASTORE_SNAPSHOT_CREATE", "DATASTORE_SNAPSHOT_UPDATE", "DATASTORE_SNAPSHOT_DELETE", "DATASTORE_RESTORE"}[i]
}
func ParseDatastoresGetResponse_allowedOperations(v string) (any, error) {
    result := DATASTORE_CREATE_DATASTORESGETRESPONSE_ALLOWEDOPERATIONS
    switch v {
        case "DATASTORE_CREATE":
            result = DATASTORE_CREATE_DATASTORESGETRESPONSE_ALLOWEDOPERATIONS
        case "DATASTORE_DELETE":
            result = DATASTORE_DELETE_DATASTORESGETRESPONSE_ALLOWEDOPERATIONS
        case "DATASTORE_BACKUP_CREATE":
            result = DATASTORE_BACKUP_CREATE_DATASTORESGETRESPONSE_ALLOWEDOPERATIONS
        case "DATASTORE_BACKUP_UPDATE":
            result = DATASTORE_BACKUP_UPDATE_DATASTORESGETRESPONSE_ALLOWEDOPERATIONS
        case "DATASTORE_BACKUP_DELETE":
            result = DATASTORE_BACKUP_DELETE_DATASTORESGETRESPONSE_ALLOWEDOPERATIONS
        case "DATASTORE_SNAPSHOT_CREATE":
            result = DATASTORE_SNAPSHOT_CREATE_DATASTORESGETRESPONSE_ALLOWEDOPERATIONS
        case "DATASTORE_SNAPSHOT_UPDATE":
            result = DATASTORE_SNAPSHOT_UPDATE_DATASTORESGETRESPONSE_ALLOWEDOPERATIONS
        case "DATASTORE_SNAPSHOT_DELETE":
            result = DATASTORE_SNAPSHOT_DELETE_DATASTORESGETRESPONSE_ALLOWEDOPERATIONS
        case "DATASTORE_RESTORE":
            result = DATASTORE_RESTORE_DATASTORESGETRESPONSE_ALLOWEDOPERATIONS
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeDatastoresGetResponse_allowedOperations(values []DatastoresGetResponse_allowedOperations) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i DatastoresGetResponse_allowedOperations) isMultiValue() bool {
    return false
}
