// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package server

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func ServerResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "An identifier for the resource, usually a UUID.",
				MarkdownDescription: "An identifier for the resource, usually a UUID.",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "A system specified name for the resource.",
				MarkdownDescription: "A system specified name for the resource.",
			},
			"system_id": schema.StringAttribute{
				Required:            true,
				Description:         "Unique Identifier of the system, usually a UUID.",
				MarkdownDescription: "Unique Identifier of the system, usually a UUID.",
			},
		},
	}
}

type ServerModel struct {
	Id       types.String `tfsdk:"id"`
	Name     types.String `tfsdk:"name"`
	SystemId types.String `tfsdk:"system_id"`
}
