// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package server

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func ServerResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"esx_root_credential_id": schema.StringAttribute{
				Required:            true,
				Description:         "ID corresponding to the ESXi password",
				MarkdownDescription: "ID corresponding to the ESXi password",
			},
			"hypervisor_host": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"hypervisor_cluster_id": schema.StringAttribute{
						Required:            true,
						Description:         "UUID of hypervisor cluster",
						MarkdownDescription: "UUID of hypervisor cluster",
					},
					"hypervisor_cluster_name": schema.StringAttribute{
						Computed: true,
					},
					"hypervisor_host_ip": schema.StringAttribute{
						Required:            true,
						Description:         "IP address of hypervisor server",
						MarkdownDescription: "IP address of hypervisor server",
					},
					"id": schema.StringAttribute{
						Computed: true,
					},
					"name": schema.StringAttribute{
						Computed: true,
					},
				},
				CustomType: HypervisorHostType{
					ObjectType: types.ObjectType{
						AttrTypes: HypervisorHostValue{}.AttributeTypes(ctx),
					},
				},
				Required:            true,
				Description:         "hypervisor host details",
				MarkdownDescription: "hypervisor host details",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "An identifier for the resource, usually a UUID.",
				MarkdownDescription: "An identifier for the resource, usually a UUID.",
			},
			"ilo_admin_credential_id": schema.StringAttribute{
				Required:            true,
				Description:         "ID corresponding to the ilo admin credential",
				MarkdownDescription: "ID corresponding to the ilo admin credential",
			},
			"ilo_network_info": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"gateway": schema.StringAttribute{
						Required:            true,
						Description:         "IP address of ilo gateway",
						MarkdownDescription: "IP address of ilo gateway",
					},
					"ilo_ip": schema.StringAttribute{
						Required:            true,
						Description:         "IP address of ilo",
						MarkdownDescription: "IP address of ilo",
					},
					"subnet_mask": schema.StringAttribute{
						Required:            true,
						Description:         "subnet of ilo gateway, eg 255.255.255.0",
						MarkdownDescription: "subnet of ilo gateway, eg 255.255.255.0",
					},
				},
				CustomType: IloNetworkInfoType{
					ObjectType: types.ObjectType{
						AttrTypes: IloNetworkInfoValue{}.AttributeTypes(ctx),
					},
				},
				Required:            true,
				Description:         "ilo network information",
				MarkdownDescription: "ilo network information",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "A system specified name for the resource.",
				MarkdownDescription: "A system specified name for the resource.",
			},
			"serial_number": schema.StringAttribute{
				Computed:            true,
				Description:         "Server's serial number.",
				MarkdownDescription: "Server's serial number.",
			},
			"server_network": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"data_ip_infos": schema.ListNestedAttribute{
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"ip_address": schema.StringAttribute{
										Required:            true,
										Description:         "IP address",
										MarkdownDescription: "IP address",
									},
								},
								CustomType: DataIpInfosType{
									ObjectType: types.ObjectType{
										AttrTypes: DataIpInfosValue{}.AttributeTypes(ctx),
									},
								},
							},
							Required:            true,
							Description:         "Details of data network",
							MarkdownDescription: "Details of data network",
						},
						"esx_ip_address": schema.StringAttribute{
							Required:            true,
							Description:         "Initial IP address of the hypervisor server",
							MarkdownDescription: "Initial IP address of the hypervisor server",
						},
					},
					CustomType: ServerNetworkType{
						ObjectType: types.ObjectType{
							AttrTypes: ServerNetworkValue{}.AttributeTypes(ctx),
						},
					},
				},
				Required:            true,
				Description:         "Details of network (and other info) for a server.",
				MarkdownDescription: "Details of network (and other info) for a server.",
			},
			"system_id": schema.StringAttribute{
				Required:            true,
				Description:         "Unique identifier of the system, usually a UUID.",
				MarkdownDescription: "Unique identifier of the system, usually a UUID.",
			},
		},
	}
}

type ServerModel struct {
	EsxRootCredentialId  types.String        `tfsdk:"esx_root_credential_id"`
	HypervisorHost       HypervisorHostValue `tfsdk:"hypervisor_host"`
	Id                   types.String        `tfsdk:"id"`
	IloAdminCredentialId types.String        `tfsdk:"ilo_admin_credential_id"`
	IloNetworkInfo       IloNetworkInfoValue `tfsdk:"ilo_network_info"`
	Name                 types.String        `tfsdk:"name"`
	SerialNumber         types.String        `tfsdk:"serial_number"`
	ServerNetwork        types.List          `tfsdk:"server_network"`
	SystemId             types.String        `tfsdk:"system_id"`
}

var _ basetypes.ObjectTypable = HypervisorHostType{}

type HypervisorHostType struct {
	basetypes.ObjectType
}

func (t HypervisorHostType) Equal(o attr.Type) bool {
	other, ok := o.(HypervisorHostType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t HypervisorHostType) String() string {
	return "HypervisorHostType"
}

func (t HypervisorHostType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	hypervisorClusterIdAttribute, ok := attributes["hypervisor_cluster_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`hypervisor_cluster_id is missing from object`)

		return nil, diags
	}

	hypervisorClusterIdVal, ok := hypervisorClusterIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`hypervisor_cluster_id expected to be basetypes.StringValue, was: %T`, hypervisorClusterIdAttribute))
	}

	hypervisorClusterNameAttribute, ok := attributes["hypervisor_cluster_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`hypervisor_cluster_name is missing from object`)

		return nil, diags
	}

	hypervisorClusterNameVal, ok := hypervisorClusterNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`hypervisor_cluster_name expected to be basetypes.StringValue, was: %T`, hypervisorClusterNameAttribute))
	}

	hypervisorHostIpAttribute, ok := attributes["hypervisor_host_ip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`hypervisor_host_ip is missing from object`)

		return nil, diags
	}

	hypervisorHostIpVal, ok := hypervisorHostIpAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`hypervisor_host_ip expected to be basetypes.StringValue, was: %T`, hypervisorHostIpAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return HypervisorHostValue{
		HypervisorClusterId:   hypervisorClusterIdVal,
		HypervisorClusterName: hypervisorClusterNameVal,
		HypervisorHostIp:      hypervisorHostIpVal,
		Id:                    idVal,
		Name:                  nameVal,
		state:                 attr.ValueStateKnown,
	}, diags
}

func NewHypervisorHostValueNull() HypervisorHostValue {
	return HypervisorHostValue{
		state: attr.ValueStateNull,
	}
}

func NewHypervisorHostValueUnknown() HypervisorHostValue {
	return HypervisorHostValue{
		state: attr.ValueStateUnknown,
	}
}

func NewHypervisorHostValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (HypervisorHostValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing HypervisorHostValue Attribute Value",
				"While creating a HypervisorHostValue value, a missing attribute value was detected. "+
					"A HypervisorHostValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("HypervisorHostValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid HypervisorHostValue Attribute Type",
				"While creating a HypervisorHostValue value, an invalid attribute value was detected. "+
					"A HypervisorHostValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("HypervisorHostValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("HypervisorHostValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra HypervisorHostValue Attribute Value",
				"While creating a HypervisorHostValue value, an extra attribute value was detected. "+
					"A HypervisorHostValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra HypervisorHostValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewHypervisorHostValueUnknown(), diags
	}

	hypervisorClusterIdAttribute, ok := attributes["hypervisor_cluster_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`hypervisor_cluster_id is missing from object`)

		return NewHypervisorHostValueUnknown(), diags
	}

	hypervisorClusterIdVal, ok := hypervisorClusterIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`hypervisor_cluster_id expected to be basetypes.StringValue, was: %T`, hypervisorClusterIdAttribute))
	}

	hypervisorClusterNameAttribute, ok := attributes["hypervisor_cluster_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`hypervisor_cluster_name is missing from object`)

		return NewHypervisorHostValueUnknown(), diags
	}

	hypervisorClusterNameVal, ok := hypervisorClusterNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`hypervisor_cluster_name expected to be basetypes.StringValue, was: %T`, hypervisorClusterNameAttribute))
	}

	hypervisorHostIpAttribute, ok := attributes["hypervisor_host_ip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`hypervisor_host_ip is missing from object`)

		return NewHypervisorHostValueUnknown(), diags
	}

	hypervisorHostIpVal, ok := hypervisorHostIpAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`hypervisor_host_ip expected to be basetypes.StringValue, was: %T`, hypervisorHostIpAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewHypervisorHostValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewHypervisorHostValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	if diags.HasError() {
		return NewHypervisorHostValueUnknown(), diags
	}

	return HypervisorHostValue{
		HypervisorClusterId:   hypervisorClusterIdVal,
		HypervisorClusterName: hypervisorClusterNameVal,
		HypervisorHostIp:      hypervisorHostIpVal,
		Id:                    idVal,
		Name:                  nameVal,
		state:                 attr.ValueStateKnown,
	}, diags
}

func NewHypervisorHostValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) HypervisorHostValue {
	object, diags := NewHypervisorHostValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewHypervisorHostValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t HypervisorHostType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewHypervisorHostValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewHypervisorHostValueUnknown(), nil
	}

	if in.IsNull() {
		return NewHypervisorHostValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewHypervisorHostValueMust(HypervisorHostValue{}.AttributeTypes(ctx), attributes), nil
}

func (t HypervisorHostType) ValueType(ctx context.Context) attr.Value {
	return HypervisorHostValue{}
}

var _ basetypes.ObjectValuable = HypervisorHostValue{}

type HypervisorHostValue struct {
	HypervisorClusterId   basetypes.StringValue `tfsdk:"hypervisor_cluster_id"`
	HypervisorClusterName basetypes.StringValue `tfsdk:"hypervisor_cluster_name"`
	HypervisorHostIp      basetypes.StringValue `tfsdk:"hypervisor_host_ip"`
	Id                    basetypes.StringValue `tfsdk:"id"`
	Name                  basetypes.StringValue `tfsdk:"name"`
	state                 attr.ValueState
}

func (v HypervisorHostValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 5)

	var val tftypes.Value
	var err error

	attrTypes["hypervisor_cluster_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["hypervisor_cluster_name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["hypervisor_host_ip"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 5)

		val, err = v.HypervisorClusterId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["hypervisor_cluster_id"] = val

		val, err = v.HypervisorClusterName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["hypervisor_cluster_name"] = val

		val, err = v.HypervisorHostIp.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["hypervisor_host_ip"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v HypervisorHostValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v HypervisorHostValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v HypervisorHostValue) String() string {
	return "HypervisorHostValue"
}

func (v HypervisorHostValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"hypervisor_cluster_id":   basetypes.StringType{},
		"hypervisor_cluster_name": basetypes.StringType{},
		"hypervisor_host_ip":      basetypes.StringType{},
		"id":                      basetypes.StringType{},
		"name":                    basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"hypervisor_cluster_id":   v.HypervisorClusterId,
			"hypervisor_cluster_name": v.HypervisorClusterName,
			"hypervisor_host_ip":      v.HypervisorHostIp,
			"id":                      v.Id,
			"name":                    v.Name,
		})

	return objVal, diags
}

func (v HypervisorHostValue) Equal(o attr.Value) bool {
	other, ok := o.(HypervisorHostValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.HypervisorClusterId.Equal(other.HypervisorClusterId) {
		return false
	}

	if !v.HypervisorClusterName.Equal(other.HypervisorClusterName) {
		return false
	}

	if !v.HypervisorHostIp.Equal(other.HypervisorHostIp) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	return true
}

func (v HypervisorHostValue) Type(ctx context.Context) attr.Type {
	return HypervisorHostType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v HypervisorHostValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"hypervisor_cluster_id":   basetypes.StringType{},
		"hypervisor_cluster_name": basetypes.StringType{},
		"hypervisor_host_ip":      basetypes.StringType{},
		"id":                      basetypes.StringType{},
		"name":                    basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = IloNetworkInfoType{}

type IloNetworkInfoType struct {
	basetypes.ObjectType
}

func (t IloNetworkInfoType) Equal(o attr.Type) bool {
	other, ok := o.(IloNetworkInfoType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t IloNetworkInfoType) String() string {
	return "IloNetworkInfoType"
}

func (t IloNetworkInfoType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	gatewayAttribute, ok := attributes["gateway"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`gateway is missing from object`)

		return nil, diags
	}

	gatewayVal, ok := gatewayAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`gateway expected to be basetypes.StringValue, was: %T`, gatewayAttribute))
	}

	iloIpAttribute, ok := attributes["ilo_ip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ilo_ip is missing from object`)

		return nil, diags
	}

	iloIpVal, ok := iloIpAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ilo_ip expected to be basetypes.StringValue, was: %T`, iloIpAttribute))
	}

	subnetMaskAttribute, ok := attributes["subnet_mask"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`subnet_mask is missing from object`)

		return nil, diags
	}

	subnetMaskVal, ok := subnetMaskAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`subnet_mask expected to be basetypes.StringValue, was: %T`, subnetMaskAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return IloNetworkInfoValue{
		Gateway:    gatewayVal,
		IloIp:      iloIpVal,
		SubnetMask: subnetMaskVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewIloNetworkInfoValueNull() IloNetworkInfoValue {
	return IloNetworkInfoValue{
		state: attr.ValueStateNull,
	}
}

func NewIloNetworkInfoValueUnknown() IloNetworkInfoValue {
	return IloNetworkInfoValue{
		state: attr.ValueStateUnknown,
	}
}

func NewIloNetworkInfoValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (IloNetworkInfoValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing IloNetworkInfoValue Attribute Value",
				"While creating a IloNetworkInfoValue value, a missing attribute value was detected. "+
					"A IloNetworkInfoValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("IloNetworkInfoValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid IloNetworkInfoValue Attribute Type",
				"While creating a IloNetworkInfoValue value, an invalid attribute value was detected. "+
					"A IloNetworkInfoValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("IloNetworkInfoValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("IloNetworkInfoValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra IloNetworkInfoValue Attribute Value",
				"While creating a IloNetworkInfoValue value, an extra attribute value was detected. "+
					"A IloNetworkInfoValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra IloNetworkInfoValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewIloNetworkInfoValueUnknown(), diags
	}

	gatewayAttribute, ok := attributes["gateway"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`gateway is missing from object`)

		return NewIloNetworkInfoValueUnknown(), diags
	}

	gatewayVal, ok := gatewayAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`gateway expected to be basetypes.StringValue, was: %T`, gatewayAttribute))
	}

	iloIpAttribute, ok := attributes["ilo_ip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ilo_ip is missing from object`)

		return NewIloNetworkInfoValueUnknown(), diags
	}

	iloIpVal, ok := iloIpAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ilo_ip expected to be basetypes.StringValue, was: %T`, iloIpAttribute))
	}

	subnetMaskAttribute, ok := attributes["subnet_mask"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`subnet_mask is missing from object`)

		return NewIloNetworkInfoValueUnknown(), diags
	}

	subnetMaskVal, ok := subnetMaskAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`subnet_mask expected to be basetypes.StringValue, was: %T`, subnetMaskAttribute))
	}

	if diags.HasError() {
		return NewIloNetworkInfoValueUnknown(), diags
	}

	return IloNetworkInfoValue{
		Gateway:    gatewayVal,
		IloIp:      iloIpVal,
		SubnetMask: subnetMaskVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewIloNetworkInfoValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) IloNetworkInfoValue {
	object, diags := NewIloNetworkInfoValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewIloNetworkInfoValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t IloNetworkInfoType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewIloNetworkInfoValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewIloNetworkInfoValueUnknown(), nil
	}

	if in.IsNull() {
		return NewIloNetworkInfoValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewIloNetworkInfoValueMust(IloNetworkInfoValue{}.AttributeTypes(ctx), attributes), nil
}

func (t IloNetworkInfoType) ValueType(ctx context.Context) attr.Value {
	return IloNetworkInfoValue{}
}

var _ basetypes.ObjectValuable = IloNetworkInfoValue{}

type IloNetworkInfoValue struct {
	Gateway    basetypes.StringValue `tfsdk:"gateway"`
	IloIp      basetypes.StringValue `tfsdk:"ilo_ip"`
	SubnetMask basetypes.StringValue `tfsdk:"subnet_mask"`
	state      attr.ValueState
}

func (v IloNetworkInfoValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["gateway"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["ilo_ip"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["subnet_mask"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.Gateway.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["gateway"] = val

		val, err = v.IloIp.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ilo_ip"] = val

		val, err = v.SubnetMask.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["subnet_mask"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v IloNetworkInfoValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v IloNetworkInfoValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v IloNetworkInfoValue) String() string {
	return "IloNetworkInfoValue"
}

func (v IloNetworkInfoValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"gateway":     basetypes.StringType{},
		"ilo_ip":      basetypes.StringType{},
		"subnet_mask": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"gateway":     v.Gateway,
			"ilo_ip":      v.IloIp,
			"subnet_mask": v.SubnetMask,
		})

	return objVal, diags
}

func (v IloNetworkInfoValue) Equal(o attr.Value) bool {
	other, ok := o.(IloNetworkInfoValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Gateway.Equal(other.Gateway) {
		return false
	}

	if !v.IloIp.Equal(other.IloIp) {
		return false
	}

	if !v.SubnetMask.Equal(other.SubnetMask) {
		return false
	}

	return true
}

func (v IloNetworkInfoValue) Type(ctx context.Context) attr.Type {
	return IloNetworkInfoType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v IloNetworkInfoValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"gateway":     basetypes.StringType{},
		"ilo_ip":      basetypes.StringType{},
		"subnet_mask": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = ServerNetworkType{}

type ServerNetworkType struct {
	basetypes.ObjectType
}

func (t ServerNetworkType) Equal(o attr.Type) bool {
	other, ok := o.(ServerNetworkType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ServerNetworkType) String() string {
	return "ServerNetworkType"
}

func (t ServerNetworkType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	dataIpInfosAttribute, ok := attributes["data_ip_infos"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`data_ip_infos is missing from object`)

		return nil, diags
	}

	dataIpInfosVal, ok := dataIpInfosAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`data_ip_infos expected to be basetypes.ListValue, was: %T`, dataIpInfosAttribute))
	}

	esxIpAddressAttribute, ok := attributes["esx_ip_address"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`esx_ip_address is missing from object`)

		return nil, diags
	}

	esxIpAddressVal, ok := esxIpAddressAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`esx_ip_address expected to be basetypes.StringValue, was: %T`, esxIpAddressAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ServerNetworkValue{
		DataIpInfos:  dataIpInfosVal,
		EsxIpAddress: esxIpAddressVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewServerNetworkValueNull() ServerNetworkValue {
	return ServerNetworkValue{
		state: attr.ValueStateNull,
	}
}

func NewServerNetworkValueUnknown() ServerNetworkValue {
	return ServerNetworkValue{
		state: attr.ValueStateUnknown,
	}
}

func NewServerNetworkValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ServerNetworkValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ServerNetworkValue Attribute Value",
				"While creating a ServerNetworkValue value, a missing attribute value was detected. "+
					"A ServerNetworkValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ServerNetworkValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ServerNetworkValue Attribute Type",
				"While creating a ServerNetworkValue value, an invalid attribute value was detected. "+
					"A ServerNetworkValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ServerNetworkValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ServerNetworkValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ServerNetworkValue Attribute Value",
				"While creating a ServerNetworkValue value, an extra attribute value was detected. "+
					"A ServerNetworkValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ServerNetworkValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewServerNetworkValueUnknown(), diags
	}

	dataIpInfosAttribute, ok := attributes["data_ip_infos"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`data_ip_infos is missing from object`)

		return NewServerNetworkValueUnknown(), diags
	}

	dataIpInfosVal, ok := dataIpInfosAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`data_ip_infos expected to be basetypes.ListValue, was: %T`, dataIpInfosAttribute))
	}

	esxIpAddressAttribute, ok := attributes["esx_ip_address"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`esx_ip_address is missing from object`)

		return NewServerNetworkValueUnknown(), diags
	}

	esxIpAddressVal, ok := esxIpAddressAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`esx_ip_address expected to be basetypes.StringValue, was: %T`, esxIpAddressAttribute))
	}

	if diags.HasError() {
		return NewServerNetworkValueUnknown(), diags
	}

	return ServerNetworkValue{
		DataIpInfos:  dataIpInfosVal,
		EsxIpAddress: esxIpAddressVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewServerNetworkValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ServerNetworkValue {
	object, diags := NewServerNetworkValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewServerNetworkValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ServerNetworkType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewServerNetworkValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewServerNetworkValueUnknown(), nil
	}

	if in.IsNull() {
		return NewServerNetworkValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewServerNetworkValueMust(ServerNetworkValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ServerNetworkType) ValueType(ctx context.Context) attr.Value {
	return ServerNetworkValue{}
}

var _ basetypes.ObjectValuable = ServerNetworkValue{}

type ServerNetworkValue struct {
	DataIpInfos  basetypes.ListValue   `tfsdk:"data_ip_infos"`
	EsxIpAddress basetypes.StringValue `tfsdk:"esx_ip_address"`
	state        attr.ValueState
}

func (v ServerNetworkValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["data_ip_infos"] = basetypes.ListType{
		ElemType: DataIpInfosValue{}.Type(ctx),
	}.TerraformType(ctx)
	attrTypes["esx_ip_address"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.DataIpInfos.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["data_ip_infos"] = val

		val, err = v.EsxIpAddress.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["esx_ip_address"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ServerNetworkValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ServerNetworkValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ServerNetworkValue) String() string {
	return "ServerNetworkValue"
}

func (v ServerNetworkValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	dataIpInfos := types.ListValueMust(
		DataIpInfosType{
			basetypes.ObjectType{
				AttrTypes: DataIpInfosValue{}.AttributeTypes(ctx),
			},
		},
		v.DataIpInfos.Elements(),
	)

	if v.DataIpInfos.IsNull() {
		dataIpInfos = types.ListNull(
			DataIpInfosType{
				basetypes.ObjectType{
					AttrTypes: DataIpInfosValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	if v.DataIpInfos.IsUnknown() {
		dataIpInfos = types.ListUnknown(
			DataIpInfosType{
				basetypes.ObjectType{
					AttrTypes: DataIpInfosValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	attributeTypes := map[string]attr.Type{
		"data_ip_infos": basetypes.ListType{
			ElemType: DataIpInfosValue{}.Type(ctx),
		},
		"esx_ip_address": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"data_ip_infos":  dataIpInfos,
			"esx_ip_address": v.EsxIpAddress,
		})

	return objVal, diags
}

func (v ServerNetworkValue) Equal(o attr.Value) bool {
	other, ok := o.(ServerNetworkValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.DataIpInfos.Equal(other.DataIpInfos) {
		return false
	}

	if !v.EsxIpAddress.Equal(other.EsxIpAddress) {
		return false
	}

	return true
}

func (v ServerNetworkValue) Type(ctx context.Context) attr.Type {
	return ServerNetworkType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ServerNetworkValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"data_ip_infos": basetypes.ListType{
			ElemType: DataIpInfosValue{}.Type(ctx),
		},
		"esx_ip_address": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = DataIpInfosType{}

type DataIpInfosType struct {
	basetypes.ObjectType
}

func (t DataIpInfosType) Equal(o attr.Type) bool {
	other, ok := o.(DataIpInfosType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t DataIpInfosType) String() string {
	return "DataIpInfosType"
}

func (t DataIpInfosType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	ipAddressAttribute, ok := attributes["ip_address"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip_address is missing from object`)

		return nil, diags
	}

	ipAddressVal, ok := ipAddressAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip_address expected to be basetypes.StringValue, was: %T`, ipAddressAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return DataIpInfosValue{
		IpAddress: ipAddressVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewDataIpInfosValueNull() DataIpInfosValue {
	return DataIpInfosValue{
		state: attr.ValueStateNull,
	}
}

func NewDataIpInfosValueUnknown() DataIpInfosValue {
	return DataIpInfosValue{
		state: attr.ValueStateUnknown,
	}
}

func NewDataIpInfosValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (DataIpInfosValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing DataIpInfosValue Attribute Value",
				"While creating a DataIpInfosValue value, a missing attribute value was detected. "+
					"A DataIpInfosValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DataIpInfosValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid DataIpInfosValue Attribute Type",
				"While creating a DataIpInfosValue value, an invalid attribute value was detected. "+
					"A DataIpInfosValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DataIpInfosValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("DataIpInfosValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra DataIpInfosValue Attribute Value",
				"While creating a DataIpInfosValue value, an extra attribute value was detected. "+
					"A DataIpInfosValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra DataIpInfosValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewDataIpInfosValueUnknown(), diags
	}

	ipAddressAttribute, ok := attributes["ip_address"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip_address is missing from object`)

		return NewDataIpInfosValueUnknown(), diags
	}

	ipAddressVal, ok := ipAddressAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip_address expected to be basetypes.StringValue, was: %T`, ipAddressAttribute))
	}

	if diags.HasError() {
		return NewDataIpInfosValueUnknown(), diags
	}

	return DataIpInfosValue{
		IpAddress: ipAddressVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewDataIpInfosValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) DataIpInfosValue {
	object, diags := NewDataIpInfosValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewDataIpInfosValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t DataIpInfosType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewDataIpInfosValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewDataIpInfosValueUnknown(), nil
	}

	if in.IsNull() {
		return NewDataIpInfosValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewDataIpInfosValueMust(DataIpInfosValue{}.AttributeTypes(ctx), attributes), nil
}

func (t DataIpInfosType) ValueType(ctx context.Context) attr.Value {
	return DataIpInfosValue{}
}

var _ basetypes.ObjectValuable = DataIpInfosValue{}

type DataIpInfosValue struct {
	IpAddress basetypes.StringValue `tfsdk:"ip_address"`
	state     attr.ValueState
}

func (v DataIpInfosValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["ip_address"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.IpAddress.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ip_address"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v DataIpInfosValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v DataIpInfosValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v DataIpInfosValue) String() string {
	return "DataIpInfosValue"
}

func (v DataIpInfosValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"ip_address": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"ip_address": v.IpAddress,
		})

	return objVal, diags
}

func (v DataIpInfosValue) Equal(o attr.Value) bool {
	other, ok := o.(DataIpInfosValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.IpAddress.Equal(other.IpAddress) {
		return false
	}

	return true
}

func (v DataIpInfosValue) Type(ctx context.Context) attr.Type {
	return DataIpInfosType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v DataIpInfosValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"ip_address": basetypes.StringType{},
	}
}
