package servers
// Resource Component Redundancy Status. Indicated as ENUM with following mapping
type ServersGetResponse_items_health_powerSuppliesRedundancy int

const (
    REDUNDANT_SERVERSGETRESPONSE_ITEMS_HEALTH_POWERSUPPLIESREDUNDANCY ServersGetResponse_items_health_powerSuppliesRedundancy = iota
    NONREDUNDANT_SERVERSGETRESPONSE_ITEMS_HEALTH_POWERSUPPLIESREDUNDANCY
    FAILEDREDUNDANT_SERVERSGETRESPONSE_ITEMS_HEALTH_POWERSUPPLIESREDUNDANCY
    ABSENT_SERVERSGETRESPONSE_ITEMS_HEALTH_POWERSUPPLIESREDUNDANCY
    DISABLED_SERVERSGETRESPONSE_ITEMS_HEALTH_POWERSUPPLIESREDUNDANCY
    OFFLINE_SERVERSGETRESPONSE_ITEMS_HEALTH_POWERSUPPLIESREDUNDANCY
    UNAVAILABLEOFFLINE_SERVERSGETRESPONSE_ITEMS_HEALTH_POWERSUPPLIESREDUNDANCY
    STANDBYOFFLINE_SERVERSGETRESPONSE_ITEMS_HEALTH_POWERSUPPLIESREDUNDANCY
    UNKNOWN_SERVERSGETRESPONSE_ITEMS_HEALTH_POWERSUPPLIESREDUNDANCY
)

func (i ServersGetResponse_items_health_powerSuppliesRedundancy) String() string {
    return []string{"REDUNDANT", "NONREDUNDANT", "FAILEDREDUNDANT", "ABSENT", "DISABLED", "OFFLINE", "UNAVAILABLEOFFLINE", "STANDBYOFFLINE", "UNKNOWN"}[i]
}
func ParseServersGetResponse_items_health_powerSuppliesRedundancy(v string) (any, error) {
    result := REDUNDANT_SERVERSGETRESPONSE_ITEMS_HEALTH_POWERSUPPLIESREDUNDANCY
    switch v {
        case "REDUNDANT":
            result = REDUNDANT_SERVERSGETRESPONSE_ITEMS_HEALTH_POWERSUPPLIESREDUNDANCY
        case "NONREDUNDANT":
            result = NONREDUNDANT_SERVERSGETRESPONSE_ITEMS_HEALTH_POWERSUPPLIESREDUNDANCY
        case "FAILEDREDUNDANT":
            result = FAILEDREDUNDANT_SERVERSGETRESPONSE_ITEMS_HEALTH_POWERSUPPLIESREDUNDANCY
        case "ABSENT":
            result = ABSENT_SERVERSGETRESPONSE_ITEMS_HEALTH_POWERSUPPLIESREDUNDANCY
        case "DISABLED":
            result = DISABLED_SERVERSGETRESPONSE_ITEMS_HEALTH_POWERSUPPLIESREDUNDANCY
        case "OFFLINE":
            result = OFFLINE_SERVERSGETRESPONSE_ITEMS_HEALTH_POWERSUPPLIESREDUNDANCY
        case "UNAVAILABLEOFFLINE":
            result = UNAVAILABLEOFFLINE_SERVERSGETRESPONSE_ITEMS_HEALTH_POWERSUPPLIESREDUNDANCY
        case "STANDBYOFFLINE":
            result = STANDBYOFFLINE_SERVERSGETRESPONSE_ITEMS_HEALTH_POWERSUPPLIESREDUNDANCY
        case "UNKNOWN":
            result = UNKNOWN_SERVERSGETRESPONSE_ITEMS_HEALTH_POWERSUPPLIESREDUNDANCY
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeServersGetResponse_items_health_powerSuppliesRedundancy(values []ServersGetResponse_items_health_powerSuppliesRedundancy) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i ServersGetResponse_items_health_powerSuppliesRedundancy) isMultiValue() bool {
    return false
}
