# Copyright 2024 Hewlett Packard Enterprise Development LP
name: Docs

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  docs:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.22.3'
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5
          # set wrapper to false, otherwise any time
          # terraform is run the first line of stdout is
          # the path to the terraform binary. This causes
          # eg the output of "terraform providers schema -json"
          # be unusable 
          terraform_wrapper: false
      - run: make install-experimental
      - run: go install github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs@v0.19.4
      - run: make docs
