# Copyright 2024 Hewlett Packard Enterprise Development LP
name: Lint

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        go: [ '1.22.3' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.51.0
      - run: make lint
